name: vap_player_plugin
description: "Flutter VAP Animation Player."
version: 0.0.1
homepage: https://github.com/aayush-dev-001/flutter-vap-player
repository: https://github.com/aayush-dev-001/flutter-vap-player

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.flutter.animation.vap.vap_player_plugin
        pluginClass: VapPlayerPlugin
      ios:
        pluginClass: VapPlayerPlugin

  assets:
    - assets/